### ISSUE TITLE
README.md missing important instruction to unblacklist spi module

### ISSUE THREAD

**Issue by bulletmark** [thomasmacpherson/piface#6]
I received my piface today and used this README to get it going. Thanks. FYI, I only run my RPi as a server (no screen or keyboard attached) via ssh and only had to do the following to get the python interface working:

sudo apt-get install python-dev git
git clone https://github.com/thomasmacpherson/piface.git
cd piface/python
sudo python setup.py install
sudo ../scripts/spidev-setup (so I could use spidev as user pi, not root).

All good, except that I also need to disable the "blacklist spi-bc2708" line in /etc/modprobe.d/raspi-blacklist.conf by commenting it out. This should be added to the README.md (and why would the Raspbian people disable the spi module from loading? - Perhaps query them to change it?)

Another minor comment is that a new user needs a schematic for input/output numbering, jumpers, etc. It seems the pifacedigitaldatasheet.pdf document referenced from here is intended for this but it is for the old piface board. I found an updated document at http://www.farnell.com/datasheets/1684425.pdf which should perhaps be referenced?

I could not use the python test script because it assumes a gtk environment.

**Comment by bulletmark** [comment]
Further to this, if you are the author of that new Farnell pdf then note some of the python examples use pin numbers starting from 0 which is clearly not the case (anymore?).

**Comment by tompreston** [comment]
Hi,
Sorry for the delay in getting back to you!

You're right about the installation instructions. The README was wrote before Raspbian was released and is now out of date. The PDF you found is now the most recent and up-to-date documentation.

The pin numbers have been updated to use indexes 0-7 rather than 1-8 in the latest development branch. We started with 1-8 since that was how our original board was labelled. The new board uses labels 0-7 which is more computer science-y.

I'll be merging the pin changes and the update to the README (it'll now point to the Farnell PDF) later today. I hope this has helped.

**Comment by tompreston** [comment]
Oh and the GTK error coming from the test script is because it is currently testing the PiFace emulator. To change this, simply edit the file by replacing the line:

```
import piface.emulator as pfio
```

with 

```
import piface.pfio as pfio
```

The test script is mostly just for development. Unfortunately, there are a lot of confusing things in this repository. We're moving to a much simpler organisation by dividing the project up into smaller components and putting them in their own repositories. This way, you'll only have to download what you need. I'll mention this in the updated README.

**Comment by bulletmark** [comment]
FYI, I changed the test script as you say and it worked fine.

Sorry, but I think the change to split into smaller components is a step backwards. People want a single README which describes all the steps needed (it's not that complicated). That PDF file on the (proprietary company!) farnell site is a poor reference because you can't select text, you have to type commands in manually. Nobody wants to read PDF on the web, it should be html. Also, executing a random install.txt file downloaded from the internet is not something people want or trust. You should just list those commands out and let people inspect them and execute them. The README here was almost fully correct, you just needed to add that comment about the blacklist line.

**Comment by bulletmark** [comment]
Very confusing. That "master" pdf document says to use that install.txt file but that pulls from this piface github repository which you say here is not the master anymore. It has been superceded by those other 2 repos.

**Comment by tompreston** [comment]
I feel your pain with PDF's and wrapped up install files but it is important to have them so that installation is simple for inexperienced users (our target audience includes primary school children/teachers who have no interest in SPI modules).

I figured less-is-more and you can inspect the install.txt file using _less_ or [even your browser](http://pi.cs.man.ac.uk/download/install.txt) but this is less friendly to users who would rather look at the README, I agree. I'll return the install commands to make the README.md more comprehensive for users who are interested in manually installing everything (myself included). Thanks for bringing it up.

The new repositories allow us to be more modular which means that we can package things up so that they have fewer dependencies. Eventually this will make the installation process easier because it will be native to Debian and not just one massive GitHub conglomerate. This doesn't mean that this repository is no longer relevant or supported, just that the most up to date I/O software is elsewhere. I think my message is confusing, I'll update that too. Thank you.
